doctrine:
    dbal:
      default_connection: default
      connections:
        symbb:
            driver:   "%database_driver%"
            host:     "%database_host%"
            port:     "%database_port%"
            dbname:   "%database_name%"
            user:     "%database_user%"
            password: "%database_password%"
            charset:  UTF8
    orm:
        default_entity_manager:   default
        entity_managers:
            default:
                auto_mapping: false
                connection:   default
            symbb:
                auto_mapping: false
                connection:   symbb
                mappings:
                    SymBBConfigBundle: ~
                    SymBBUserBundle: ~
                    SymBBTemplateBundle: ~
                    SymBBAdminBundle: ~
                    SymBBForumBundle: ~